/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import java.util.List;

import javax.swing.table.DefaultTableModel;

import model.Categoria;
import model.Produto;
import service.CategoriaService;
import service.ProdutoService;

/**
 *
 * @author Mateus
 */
public class BuscaCategoria extends javax.swing.JFrame {

    /**
     * Creates new form Info
     */
    public BuscaCategoria() {
        initComponents();

        model = (DefaultTableModel) jTable1.getModel();
        services = new ProdutoService();
        categorias = new CategoriaService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        consulta1 = new javax.swing.JButton();
        consulta2 = new javax.swing.JButton();
        consulta3 = new javax.swing.JButton();
        consulta4 = new javax.swing.JButton();
        consulta15 = new javax.swing.JButton();
        consulta6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buscar");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Preço", "Categoria", "No estoque"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        consulta1.setText("Consulta 1");
        consulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta1ActionPerformed(evt);
            }
        });

        consulta2.setText("Consulta 2");
        consulta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta2ActionPerformed(evt);
            }
        });

        consulta3.setText("Consulta 3");
        consulta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta3ActionPerformed(evt);
            }
        });

        consulta4.setText("Consulta 4");
        consulta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta4ActionPerformed(evt);
            }
        });

        consulta15.setText("Consulta 5");
        consulta15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta15ActionPerformed(evt);
            }
        });

        consulta6.setText("Consulta 6");
        consulta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consulta4)
                    .addComponent(consulta1))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(consulta2)
                        .addGap(57, 57, 57)
                        .addComponent(consulta3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(consulta15)
                        .addGap(57, 57, 57)
                        .addComponent(consulta6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consulta1)
                    .addComponent(consulta2)
                    .addComponent(consulta3))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consulta6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(consulta4)
                        .addComponent(consulta15)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consulta1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ordemAlfabeticaActionPerformed
        carregarTabela(services.quantidadeEstoqueDesc());
    }// GEN-LAST:event_ordemAlfabeticaActionPerformed

    private void consulta2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_categoriaActionPerformed
        carregarTabela(services.mediaPreco());
    }// GEN-LAST:event_categoriaActionPerformed

    private void consulta3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_MaioeValorActionPerformed
        carregarTabela(services.totalProdutosCategoria());
    }// GEN-LAST:event_MaioeValorActionPerformed

    private void consulta4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_menorValorActionPerformed
        carregarTabela(services.mediaPreco());
    }// GEN-LAST:event_menorValorActionPerformed

    private void consulta15ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mediaCategoriaActionPerformed
        carregarTabela(services.buscaCategoria());
    }// GEN-LAST:event_mediaCategoriaActionPerformed

    private void consulta6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_QuanridadeActionPerformed
        carregarTabela(services.acimaMedia());
    }// GEN-LAST:event_QuanridadeActionPerformed

    public void carregarTabela(List<Produto> produtos) {

        model.setRowCount(0);

        try {
            for (Produto p : produtos) {
                model.addRow(new Object[] {
                        p.getId(),
                        p.getNome(),
                        p.getValor(),
                        new Categoria(p.getId_categoria(), p.getNomeCategoria()), // objeto
                        p.getEstoque()
                });
            }
            System.out.println("Tabela atualizada!");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Erro ao carregar produtos:\n" + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscaCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consulta1;
    private javax.swing.JButton consulta15;
    private javax.swing.JButton consulta2;
    private javax.swing.JButton consulta3;
    private javax.swing.JButton consulta4;
    private javax.swing.JButton consulta6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private ProdutoService services;
    private DefaultTableModel model;
    private CategoriaService categorias;
}
